const TILE_SIZE = 132;

const TILES_PER_ROW_COUNT = 2;

const TILE_GAP = 20;

const TILE_ANIMATION_DURATION = 350;

const WIN_TILE_VALUE = 2048;

export { TILES_PER_ROW_COUNT, TILE_SIZE, TILE_GAP, TILE_ANIMATION_DURATION, WIN_TILE_VALUE };
