const TILES_PER_ROW_COUNT = 4;

const TILE_ANIMATION_DURATION = 350;

const WIN_TILE_VALUE = 2048;

const MAX_SWIPE_DIFF = 30;

export { TILES_PER_ROW_COUNT, TILE_ANIMATION_DURATION, WIN_TILE_VALUE, MAX_SWIPE_DIFF };
